### ISSUE TITLE
socket_sendto error

### ISSUE THREAD

**Issue by Petah** [tylerhall/php-growl#3]
Hi, nice little library

I get this error (on Windows, using growl-for-windows, and PHP 5.3)

```
socket_sendto() [function.socket-sendto]: unable to write to socket [0]: The attempted operation is not supported for the type of object referenced.
```

It works fine if I force php-growl to use fsock instead, so I was wondering if you (or I can do it if you want) should add an option to force fsock?

**Comment by tylerhall** [comment]
I don't have a Windows machine to test with. If you have a solution, feel free to send me a pull request and I'll merge your fix into the project :)

**Comment by Petah** [comment]
Can do, how would you prefer the configuration to be set?

3 options I can think of are:
- A constant definition
- A class variable
- A static variable

I would lean towards a constant:

```
private function send($data)
{
    if(!defined('GROWL_SOCK') && function_exists('socket_create') && function_exists('socket_sendto') || GROWL_SOCK === 'socket')
    {
        ...
    }
    elseif(!defined('GROWL_SOCK') && function_exists('fsockopen') || GROWL_SOCK === 'fsock')
    {
        ...
    }

    return false;
}
```

**Comment by tylerhall** [comment]
I've merged your changes. Thanks!

**Comment by melfy** [comment]
I'm on windows and still getting this error... 

socket_sendto(): unable to write to socket [10045]: The attempted operation is not supported for the type of object referenced in Growl.class.php on line 84 

which is => socket_sendto($sck, $data, strlen($data), 0x100, $this->address, $this->port);

**Comment by tylerhall** [comment]
Thanks, but I don't have any way of testing on Windows. If you'd like to submit a fix of your own, I'll be happy to merge it into the project.
